### ISSUE TITLE
Pause and resume application when it goes to background

### ISSUE THREAD

**Issue by timbru31** [timbru31/cordova-plugin-lottie-splashscreen#1]
Currently the current frame is freezed and **not** resumed. See https://github.com/airbnb/lottie-ios/issues/413 for more information

**Comment by timbru31** [comment]
Done via c439b5e

**Comment by erikramalho** [comment]
Hey @timbru31 I’ve noticed that Splash doesn’t replay After put The app on background for a while. It’s the regular behavior using The standard  Cordova Splash screen plugin. Also I’ve tested other apps (non Cordova) and they all replay The Splash screen After pause and resume for a long time.  Does this plugin Supports this ?
