### ISSUE TITLE
RuntimeException when running on Android

### ISSUE THREAD

**Issue by StormPooper** [timbru31/cordova-plugin-lottie-splashscreen#117]
# Bug report

## What steps will reproduce the problem?

1. Install this and the Ionic plugin.
2. Run the app in the emulator (Android 9).

## Expected output

A splash screen, followed by the app itself.

## What do you see instead?

The app crashes before reaching the splash screen.

## Log file of the issue/error

https://gist.github.com/StormPooper/fc33f59a9453e2814f81f1540d64d7f9

## Version information

See comments in above gist for `ionic info` and `cordova info` output.

## Please provide any additional information below.

I've tried both with and without the original splashscreen plugin installed, with a local and a remote lottiefile and with various options from the README, but no difference. We also have both AndroidX plugins installed as per the README. I had no errors adding the plugin and no build issues, the exception happens at runtime.

## Checklist

-   [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
-   [x] I have added a valid version output
-   [x] I have attached necessary information like a screenshot, example project or videos

**Comment by timbru31** [comment]
Thanks for the report! Strange issue - have you tried to remove and re-add the plugin or platform? Did you observe any error while installing it?

**Comment by StormPooper** [comment]
Yeah, tried both of those, no errors when installing. I'll give it another go and see if it happens again then report back.

**Comment by timbru31** [comment]
I assume you can't upload your project so I can debug the issue?

**Comment by StormPooper** [comment]
Sadly not, it's a project at work, rather than a personal one.

**Comment by timbru31** [comment]
No worries, I'm just gonna ask more questions then ;)
- Does it work on iOS?
- Does it work on a native device?
- How did you build the app (manually via Android Studio, Ionic Appflow, Cordova CLI)?

**Comment by StormPooper** [comment]
Same thing after clearing out the project entirely again.

- Untested, asked a colleague to build it for me and get back to me
- Nope, same issue, just closes almost instantly
- Through Ionic CLI, which calls the Cordova CLI
- Originally tried the npm package (and my retest since then), that was me just seeing if there was any difference between the published package and the git version

**Comment by timbru31** [comment]
Thanks for the answers. I will try to setup a dummy project on the weekend with the list of your plugins both on my Mac and Win10 machine to see if I can reproduce your issue

**Comment by StormPooper** [comment]
Thanks Tim, that'd be great.

Update from my colleague, he received this when trying to build: `error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'lottie-ios')`

**Comment by StormPooper** [comment]
A colleague worked out what our issue was - our app wasn't set up to compile Kotlin code. After adding [cordova-support-kotlin](https://www.npmjs.com/package/cordova-support-kotlin) it works 😃 He was also able to build it for iOS after changing the version of Swift the pods built with, so job done. Thanks for your help.

**Comment by timbru31** [comment]
Glad to hear!

**Comment by timbru31** [comment]
In regards to

> Update from my colleague, he received this when trying to build: error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'lottie-ios')

I think the correct value to use is `5`, not `5.0`. I've just ran a test with Swift 5 and it worked for us.
