### ISSUE TITLE
View destroyed before animation finished

### ISSUE THREAD

**Issue by panczarny** [timbru31/cordova-plugin-lottie-splashscreen#133]
# Enhancement proposition

We are using a nice animation which duration is longer than initialization of application 🙄
We would like users to see the full animation, but I didn't find any possibility in this plugin to process this.

## What steps will reproduce the problem?
1. Use the `cordova-plugin-lottie-splashscreen`
2. Use animation that lasts long (longer than application init)

## Proposition
Possibility to add some preference, like
* `LottieMinimumDuration`
* `LottieAnimationDuration`
* `LottieHideAfter`
that allows to configure the duration of lottie animation.

**Comment by timbru31** [comment]
You could use the following values to keep the animation visible all the time and then decide in the JS if the animation is finished.
```
<preference name="LottieHideTimeout" value="0" /> <!-- This ensures Lottie's native view container is never -->
<preference name="LottieAutoHideSplashScreen" value="false" /> <!-- This ensures that Lottie's view container is not hidden, when the the onPageFinished (Android) or pageDidLoad (iOS) event is fired
```

Does that work in your case? Otherwise the proposed preferences make sense, i.e., hide after the animation has successfully played once (unless loop is true)

**Comment by panczarny** [comment]
Unfortunately, I still don't know how long the application has been running for, when I'm triggering it in JS.

So, could you, please, add such `pref`?

**Comment by timbru31** [comment]
> So, could you, please, add such pref?

That's why there is an `enhancement` label already ;)

---

> I cannot find, is there any fadeOut option on hiding the view?

No, currently it just hides the view without a fading effect. Good suggestion, too!

**Comment by timbru31** [comment]
I've thought about this issue again:

> LottieHideTimeout (Double, default 0). Duration in seconds after which the Lottie animation should be hidden.

Isn't this exactly the setting you need? You can set `LottieAutoHideSplashScreen` to false and the `LottieHideTimeout` to exactly your animation length?

**Comment by panczarny** [comment]
Unfortunately nope. This setting works as it is the `max time of animation duration`, not the `exact time of animation duration`

**Comment by YanDevDe** [comment]
How about adding Events such like

```
lottie.splashscreen.on("animationend", async ()=>{
   await lottie.splashscreen.hide();
});
```

Or instead events -> Preferences:
"LottieHideAfterAnimationEnd"

splashscreen will be hidden if the animations were finished and `lottie.splashscreen.hide()` were called before (or by using `LottieAutoHideSplashScreen`)

**Comment by timbru31** [comment]
Thanks for the suggestion @YanDevDe :) - Haven't thought about events yet.

**Comment by timbru31** [comment]
Moving this to the 0.8.0 milestone - our app suffers from same "bug" that it's starting too fast one some devices 😓

**Comment by timbru31** [comment]
Alright, a new beta (`0.8.0-beta.2`) has been published with support for the new events Yan suggested:

```ts
type LottieEvents = 'lottieAnimationStart' | 'lottieAnimationEnd' | 'lottieAnimationCancel' | 'lottieAnimationRepeat';

lottie.splashscreen.on(LottieEvents).then(...)
```

Please note that `lottieAnimationRepeat` is only supported on Android and that `lottieAnimationEnd` might never be dispatched in case of looping animations.

Side note: `@ionic-native` is of course **not** updated yet!

Feedback is very welcome! :)

**Comment by YanDevDe** [comment]
How will `.on("lottieAnimationRepeat").then(...)` works? 
Promise call `.then(...)` fires once and "lottieAnimationRepeat" surely need more than just one call.

Wouldn't make this more sense? Callbacks can be called multiple times:

```
type LottieEvents = 'lottieAnimationStart' | 'lottieAnimationEnd' | 'lottieAnimationCancel' | 'lottieAnimationRepeat';

lottie.splashscreen.on(LottieEvents, (...)=>{
    //...
})
```

Otherwise it looks good! =)

**Comment by timbru31** [comment]
Indeed a Promise doesn't make much sense in this case. I've added your `.once` suggestion and refactored the `.on` method to use a supplied callback function instead.  
Listening to all events can be achieved in the `.on` function if the passed event parameter is falsy.

**Comment by timbru31** [comment]
0.8.0 is released.
