### ISSUE TITLE
FadeOut preference for destroying a view

### ISSUE THREAD

**Issue by panczarny** [timbru31/cordova-plugin-lottie-splashscreen#136]
# Enhancement proposition

From https://github.com/timbru31/cordova-plugin-lottie-splashscreen/issues/133#issuecomment-567030483

Add a preference that specifies how long the fade out should last after `global.lottie.splashscreen.hide()` function was invoked. The `Promise` should `resolve` (or `reject` 🙀) after the `fadeOut` has ended.

## Proposition
Preference name:
* `LottieFadeOutDuration`
* `LottieSplashscreenFadeOutDuration`
* `LottieHideDuration`
* `LottieHidingDuration`

**Comment by timbru31** [comment]
`LottieFadeOutDuration` has been added as a new config setting. It makes on both iOS and Android an alpha animation from 1 -> 0 for a given milliseconds interval. Promise is resolved only when the fade timeout has passed, too.

**Comment by YanDevDe** [comment]
Does this fade only the lottie object itself or also background too?

**Comment by timbru31** [comment]
Should fade the whole container, i.e. background, too
