### ISSUE TITLE
Is posible to disable caching in android?

### ISSUE THREAD

**Issue by castelar007** [timbru31/cordova-plugin-lottie-splashscreen#139]
i had a firestore storage link with my data.json to have dinamic splash depending season. this aproach works perfect in ios, but android seems to caching the first data.json it loads. is there a way to disable this caching? and load the  data.json every time from firebase storage??

**Comment by timbru31** [comment]
Thanks for the issue, I’ll see if there are any options to change the caching mechanism

**Comment by timbru31** [comment]
This has been published as 0.8.0-beta.0.

**Comment by castelar007** [comment]
thank you sir!!

**Comment by timbru31** [comment]
Blocked by upstream: https://github.com/airbnb/lottie-android/issues/1289#issuecomment-570676043

**Comment by timbru31** [comment]
I'm moving this to the 0.9.0 milestone because the issue is blocked by upstream. This unblocks the 0.8.0 RC

**Comment by timbru31** [comment]
Good news, this has been fixed and will be included in the Lottie 3.3.2 release!

**Comment by castelar007** [comment]
nice

**Comment by timbru31** [comment]
Published in v0.8.1
