### ISSUE TITLE
Can't add to my ionic app please help me..

### ISSUE THREAD

**Issue by barangungor** [timbru31/cordova-plugin-lottie-splashscreen#158]
I try add your plugin to my project using this code

`ionic cordova plugin add cordova-plugin-lottie-splashscreen`

but i facing this error

`'sh' is not recognized as an internal or external command,
operable program or batch file.
Failed to install 'cordova-plugin-lottie-splashscreen': Error: Hook failed with error code ENOENT: C:\Users\bbara\Desktop\GuvercinSepetim\plugins\cordova-plugin-lottie-splashscreen\hooks\ios\update_pod_repo.sh
    at C:\Users\bbara\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:224:23
    at _rejected (C:\Users\bbara\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
    at C:\Users\bbara\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\bbara\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\bbara\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
    at C:\Users\bbara\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\bbara\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\bbara\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
Hook failed with error code ENOENT: C:\Users\bbara\Desktop\GuvercinSepetim\plugins\cordova-plugin-lottie-splashscreen\hooks\ios\update_pod_repo.sh
    at processTicksAndRejections (internal/process/next_tick.js:74:9)`

**Comment by timbru31** [comment]
You are trying to build iOS on a Windows machine - that's not possible.

**Comment by barangungor** [comment]
WHAT? Only run plugin add code.

**Comment by timbru31** [comment]
What's your output of `cordova platfrom ls` in your project folder?

**Comment by barangungor** [comment]
```
Installed platforms:
  android 8.1.0
  ios 5.1.1
Available platforms:
  browser ^6.0.0
  electron ^1.0.0
  osx ^5.0.0
  windows ^7.0.0

```

**Comment by timbru31** [comment]
You've installed ios as an active platform, therefore this plugin executes the following hook: https://github.com/timbru31/cordova-plugin-lottie-splashscreen/blob/master/plugin.xml#L51

To solve this issue, as you can't build iOS on a non macOS machine, run the following:
1. ionic cordova platform rm ios
2. ionic cordova plugin add cordova-plugin-lottie-splashscreen

**Comment by barangungor** [comment]
Thanks , i can add your plugin but facing an error when build android
`Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> > Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED`

**Comment by timbru31** [comment]
Please create a new issue and follow the issue template. Thanks!
