### ISSUE TITLE
The background color setting does not work as expected.

### ISSUE THREAD

**Issue by UNSWZen** [timbru31/cordova-plugin-lottie-splashscreen#160]
# Bug report
I tried the plugin on android devices and there's a problem for the background color setting.
When the app load, it first shows a grey screen, then the animation shows up, with the background color remain grey for a second(I was trying to use a none full screen animation and fill up the rest area with the preset background color), after a while the background color switched to what I set in the preference)
## What steps will reproduce the problem?
Here's my splashscreen related setting in config.xml
```
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="SplashScreen" value="none" />
    <preference name="LottieAnimationLocation" value="www/assets/lottie-files/splash-loader.json" />
    <preference name="LottieLoopAnimation" value="true" />
    <preference name="ShowSplashScreenSpinner" value="false" />
    <preference name="SplashScreenDelay" value="0" />
    <preference name="FadeSplashScreen" value="false" />
    <preference name="LottieBackgroundColor" value="#000000" />
    <preference name="LottieScaleType" value="CENTER_INSIDE" />
```
Sorry I can't share the lottie file with you but I think a random none full screen animation should help you reproduce that.

## Expected output
The background color should show immediately once the animation fires up.
## What do you see instead?
The background color was filled later than the animation appear.
## Log file of the issue/error
No log files sorry. But I found out a workaround for this:
https://forum.ionicframework.com/t/2-second-long-gray-loading-screen/113840/4
The answer provided by **@soumare** does work. Just not sure if this is doable under plugin level?

## Version information
Ionic 3
Angular 5

## Please provide any additional information below.
This plugin will need to work together with cordova-plugin-splashscreen before the animation loads(show the static image instead of default cordova icon), Is there any way using only one plugin?
## Checklist

-   [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
-   [ ] I have added a valid version output
-   [ ] I have attached necessary information like a screenshot, example project or videos

**Comment by timbru31** [comment]
Thanks for your issue - I'll investigate this.

Regarding the additional question:

> Is there any way using only one plugin?

Yes, but not if you use the cordova-plugin-ionic < 5.4.0 (this commit removes the hard-coded dependency: https://github.com/ionic-team/cordova-plugin-ionic/commit/aa0c62ce72bd8cb8511b91191b18b14c8f133bc0#diff-53f390d375398624afe1cfe1125f42bf)

**Comment by timbru31** [comment]
This has to be solved on the Cordova application, not plugin level. This can be fairly easy achieved if one adds, e. g., this snippet to the `config.xml` and puts the corresponding `theme.xml` in `www/static/images/android`:

```xml
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application/activity[@android:label='@string/activity_name']" >
            <activity android:theme="@style/Theme.White"></activity>
        </edit-config>
        <resource-file src="www/static/images/android/theme.xml" target="app/src/main/res/values​​/themes.xml" />
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
	<style name="Theme.White" parent="@android:style/Theme.DeviceDefault.NoActionBar">
		<item name="android:windowBackground">@android:color/white</item>
	</style>
</resources>

```

I'll add this section to the FAQ document, though. Of course, the paths and colors can be adjusted.

Thanks again for making me aware of this strange Android behavior.
