### ISSUE TITLE
lottieAnimationEnd never called if application is too slow

### ISSUE THREAD

**Issue by YanDevDe** [timbru31/cordova-plugin-lottie-splashscreen#175]
# Bug report

## What steps will reproduce the problem?
Lets assume the animation is very very short and the deviceready event hasn't been fired yet then the Event "lottieAnimationEnd" will be never called, as example:
Animation ends in 1s, deviceready fires in 2s, then this will never be fired:

      document.addEventListener("deviceready", () => {
        lottie.splashscreen.on("lottieAnimationEnd", async () => {
          await lottie.splashscreen.hide();
          console.log("-----> lottieAnimationEnd!");
        });
        console.log("-----> deviceReady!");
      });

## Expected output

"lottieAnimationEnd" should be called directly even if animation ended before deviceReady had the chance to fire it.

## What do you see instead?

Application has been started -> 1s later Animation is ended -> 1s later deviceready is being fired, but not "lottieAnimationEnd".

I also tried without "deviceready", but even that it wont be called anyway since the application itself is not done by loading thus "lottieAnimationEnd" will never be called.

## Version information

I'm using the v0.8.0

-   [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
-   [x] I have added a valid version output
-   [ ] I have attached necessary information like a screenshot, example project or videos

**Comment by YanDevDe** [comment]
Perhaps something like lottie.splashscreen.status.lottieAnimationEnded as readonly variable to check if animation has been ended?

If its true, then it's known that "lottieAnimationEnd" event at `lottie.splashscreen.on("lottieAnimationEnd")` won't be called since the animation has been already ended before deviceready had the chance to fire.

If its false, then it's known that "lottieAnimationEnd" event can fire anytime yet.

**Comment by timbru31** [comment]
Yes, I've though about this issue, too. So far we've use the following in our app:

```ts
ngAfterViewInit() {
	race(interval(1000).pipe(take(1)), from(lottie.splashscreen.once('lottieAnimationEnd'))).subscribe(_ => this.hideSplashScreen());
}
```

Something similar with Promise.race works, too. Nevertheless, I can look into setting a readonly prop to true if the animation has ended. (And optionally if there is a nice way to ensure the fire the lottieAnimationEnd event is fired again(?) after the deviceready or kept back until the deviceready.

**Comment by YanDevDe** [comment]
readonly prop could be useful 👍 
Otherwise firing `lottieAnimationEnd` should be only fired when deviceready were called. 
It make no sense to fire before deviceready because the lottie itself can't be used before anyway. 😄

**Comment by timbru31** [comment]
I've published 0.8.1-beta.0 which includes an `animationEnded` (sync) property to check if an animation is already finished. (Usage via `lottie.splashscreen.animationEnded`). Let me know if this works/is sufficient.

**Comment by YanDevDe** [comment]
I'll test this somewhere next week (or sunday) 👍  Thanks for the work! 😊

**Comment by timbru31** [comment]
Friendly ping @YanDevDe

**Comment by YanDevDe** [comment]
Oh sorry. I tried your 0.8.1-beta.0 version and it was not working. 
I was using following code:

```
    if (lottie.splashscreen.animationEnded) {
      console.log("-----> ANIMATION ENDED BY VARIABLE!");
      await lottie.splashscreen.hide();
    } else {
      console.log(
        "-----> Animation has not been played yet... Let's listen on event"
      );
      document.addEventListener("deviceready", async () => {
        console.log("-----> DeviceReady fired");
        lottie.splashscreen.on("lottieAnimationEnd", async () => {
          console.log("-----> ANIMATION ENDED!");
          await lottie.splashscreen.hide();
        });
      });
    }
```

And the Output were:

```
-----> Animation has not been played yet... Let's listen on event
-----> DeviceReady fired
```

The splashscreen is never being hidden. The animation was already done before deviceready had the chance to fire it.

**Comment by timbru31** [comment]
Could you possibly share (the|an) example project that still shows the issue?

**Comment by YanDevDe** [comment]
When I got time. Currently it is bit hard. 👍 I'll let you know here.

**Comment by YanDevDe** [comment]
It is bit difficult to reproduce this issue on new projects where it contains almost no ressources. Cordova app is always too fast here. So I created a very very short lived animation to reproduce the issue. 
I've tried this on Nokia 2.2, a $100 smartphone. So perhaps it will be still working on faster devices. So if possible, try it out at Android Simulator!

I've only modified www/js/index.js, www/lottie/data.json and config.xml. This example is directly from timbru31/cordova-plugin-lottie-splashscreen.

Here is the repository: https://github.com/YanDevDe/cordova-plugin-lottie-splashscreen-issue

Thanks,

Yan

**Comment by timbru31** [comment]
Great, this helps. I've also have a very, very cheap Android tablet laying around  for testing 😂

**Comment by timbru31** [comment]
I've published cordova-plugin-lottie-splashscreen@0.8.1-beta.2 - this works fine in my test(s). Let me know if this solves the issue.

**Comment by YanDevDe** [comment]
Awesome! 😄I'll try out soon again!

**Comment by timbru31** [comment]
Any luck trying the beta yet? I'd like to continue with the 0.8.1 release :D

**Comment by YanDevDe** [comment]
Oh, I'm so sorry. I was so busy with my other project. I just tested it again (without any changes on code) and it seems to be not working yet. I'm still stuck on animated splashscreen.
I was testing from the repository example. (https://github.com/YanDevDe/cordova-plugin-lottie-splashscreen-issue)

With your new version: **0.8.1-beta.2** 

Output were:

```
-----> Animation has not been played yet... Let's listen on event
```

Screenshot: 
![Screenshot_20200407-175116](https://user-images.githubusercontent.com/1526048/78691075-8661cb80-78f8-11ea-8940-347c675e4bdf.png)

**Comment by timbru31** [comment]
Indeed, I've bugged that release. Probably forgot to sync my local changes back to the correct source code. Can you try 0.8.1-beta.3?

I've also pushed my changes to your issue repo (https://github.com/timbru31/cordova-plugin-lottie-splashscreen-issue) - newest release works fine on both Android and iOS for me.

**Comment by YanDevDe** [comment]
Yuup, the 0.8.1-beta.3 is working on my Android devices too! Awesome! 😄👏
