### ISSUE TITLE
iOS/Xcode: Not such module Lottie

### ISSUE THREAD

**Issue by YanDevDe** [timbru31/cordova-plugin-lottie-splashscreen#180]
# Bug report

## What steps will reproduce the problem?
When I'm trying to run (debug) the project directly in Xcode, then I'm receiving error that Lottie wasn't found. Did I missed something here?

## Expected output
No error messages

## What do you see instead?
"No such module Lottie" Error message from Xcode

## Log file of the issue/error
<img width="1146" alt="Bildschirmfoto 2020-03-02 um 10 38 28" src="https://user-images.githubusercontent.com/1526048/75664389-b0c5c680-5c72-11ea-9f63-0cc047bd0ed1.png">

## Version information

cordova-plugin-lottie-splashscreen: 0.8.0
cordova-ios: 5.1.1
cordova: 9.0.0
Xcode: 11.3.1

## Checklist

-   [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
-   [x] I have added a valid version output
-   [x] I have attached necessary information like a screenshot, example project or videos

**Comment by timbru31** [comment]
Did you open the `.xcodeproj` or `.xcworkspace` file? Always use the workspace over the project if both are present. :)

**Comment by YanDevDe** [comment]
Yup, that was the reason lol. Thanks! 😅
