### ISSUE TITLE
iOS build failed CompileSwift normal x86_64 error

### ISSUE THREAD

**Issue by takhil** [timbru31/cordova-plugin-lottie-splashscreen#213]
The following build commands failed:
	CompileSwift normal x86_64 /Users/xxx/Downloads/xxx/xx/platforms/ios/xxx//Plugins/cordova-plugin-lottie-splashscreen/LottieSplashScreen.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios exited with exit code 65.

Ionic Info:
pods: 1.8.4

Ionic:

   Ionic CLI                     : 6.6.0 
   Ionic Framework          : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.901.7
   @angular-devkit/schematics    : 9.1.4
   @angular/cli                  : 9.1.7
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.1

System:

   Android SDK Tools : 26.1.1 
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.16.2 (/usr/local/bin/node)
   npm               : 6.14.4
   OS                : macOS Catalina
   Xcode             : Xcode 11.5 Build version 11E608c

**Comment by takhil** [comment]
After removing platform and add again can able to build but again the following error shows up 


Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x600001f1ea60 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=www/assets/splashscreen/splash.json, NSErrorFailingURLKey=www/assets/splashscreen/splash.json, NSLocalizedDescription=unsupported URL}

**Comment by timbru31** [comment]
Please follow the issue template, your support request is hard to read.
Without a config.xml I'm not able to help. Make sure you've set `LottieRemoteEnabled` correctly.

**Comment by takhil** [comment]
**Config.Xml**
        <platform name="ios">
        <preference name="LottieRemoteEnabled" value="true" />
        <preference name="LottieAnimationLocation" value="www/assets/splashscreen/splash.json" />
        <preference name="LottieCancelOnTap" value="true" />
        <preference name="LottieFullScreen" value="true" />
        <preference name="LottieHideTimeout" value="0" />
        <preference name="LottieCacheDisabled" value="true" />

**Xcode error  log:**

<890A9FD3-09EC-4A3B-A68F-61A63101BCBA>.<1> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x600002cf26d0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=www/assets/splashscreen/splash.json, NSErrorFailingURLKey=www/assets/splashscreen/splash.json, NSLocalizedDescription=unsupported URL}

The operation couldn’t be completed. (Lottie.LottieDownloadError error 0.)

**Comment by timbru31** [comment]
You can’t use remote enabled with a local file, like I’ve said.
