### ISSUE TITLE
Animation not working.

### ISSUE THREAD

**Issue by tarun57** [timbru31/cordova-plugin-lottie-splashscreen#218]
I'm using ionic 3 and using lottie splash screen with animation.
Splash screen is showing but the animation is not working in ionic 3  when i run this lottie animation json file in ionic 4 project then its working fine.
The issue is in ionic 3 animation not showing in lottie splash screen but  working in ionic 4.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps me to debug the issue further and to provide a solution much faster. With important information missing, I unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

Also, without a reproduction project I'm not able to help, either. I don't have the resources to test old legacy versions of Ionic. If you can provide a "not working project", I can take a look though.

**Comment by tarun57** [comment]
here is my package.json file
![Screenshot from 2020-06-08 18-17-59](https://user-images.githubusercontent.com/43084605/84032131-788dfc80-a9b4-11ea-8a1d-6e335f58a162.png)

**Comment by timbru31** [comment]
That's a) not what I've asked for and b) not complete.

**Comment by tarun57** [comment]
![Screenshot from 2020-06-08 18-52-04](https://user-images.githubusercontent.com/43084605/84035319-2d2a1d00-a9b9-11ea-9655-2bc95afa9104.png)

**Comment by timbru31** [comment]
Again, this is not a complete list. Create a new issue, follow the template, don't use screenshots (something I can copy, i.e., text) and provide a reproduction example.
