### ISSUE TITLE
Animation not working ionic 3

### ISSUE THREAD

**Issue by tarun57** [timbru31/cordova-plugin-lottie-splashscreen#219]
In ionic 3 lotties json animation not working but its working fine in ionic 4.
Here is my package.json file.

{
  "name": "miyabi",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/android-permissions": "^4.20.0",
    "@ionic-native/app-update": "^4.20.0",
    "@ionic-native/base64": "^4.20.0",
    "@ionic-native/base64-to-gallery": "^4.20.0",
    "@ionic-native/camera": "^4.20.0",
    "@ionic-native/core": "~4.20.0",
    "@ionic-native/crop": "^4.20.0",
    "@ionic-native/file": "^4.20.0",
    "@ionic-native/file-path": "^4.20.0",
    "@ionic-native/file-transfer": "^4.20.0",
    "@ionic-native/in-app-browser": "^4.20.0",
    "@ionic-native/lottie-splash-screen": "^4.20.0",
    "@ionic-native/native-page-transitions": "^4.20.0",
    "@ionic-native/paypal": "^4.20.0",
    "@ionic-native/photo-library": "^4.20.0",
    "@ionic-native/photo-viewer": "^4.20.0",
    "@ionic-native/social-sharing": "^4.20.0",
    "@ionic-native/splash-screen": "~4.20.0",
    "@ionic-native/status-bar": "^4.20.0",
    "@ionic-native/streaming-media": "^5.22.0",
    "@ionic-native/transfer": "^3.14.0",
    "@ionic/lab": "^3.0.0",
    "@ionic/storage": "^2.2.0",
    "angular-cropperjs": "^0.1.5",
    "card.io.cordova.mobilesdk": "^2.1.0",
    "com-badrit-base64": "^0.2.0",
    "com-sarriaroman-photoviewer": "^1.2.5",
    "com.paypal.cordova.mobilesdk": "^3.5.0",
    "com.telerik.plugins.nativepagetransitions": "^0.6.5",
    "cordova-android": "^8.1.0",
    "cordova-base64-to-gallery": "^4.1.3",
    "cordova-ios": "^4.5.5",
    "cordova-plugin-add-swift-support": "^1.7.2",
    "cordova-plugin-android-permissions": "^1.0.2",
    "cordova-plugin-app-update": "^2.0.2",
    "cordova-plugin-appversion": "^1.0.0",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-crop": "^0.4.0",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-filepath": "^1.5.8",
    "cordova-plugin-google-analytics": "^1.9.0",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "cordova-plugin-inapppurchase": "^1.2.0",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.2.1",
    "cordova-plugin-lottie-splashscreen": "^0.6.0",
    "cordova-plugin-photo-library": "^2.3.1",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-streaming-media": "^2.3.0",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-plugin-x-socialsharing": "^5.6.8",
    "cordova-res": "^0.14.0",
    "cordova-sqlite-storage": "^3.4.1",
    "es6-promise-plugin": "^4.2.2",
    "html2canvas": "^1.0.0-rc.5",
    "image-to-base64": "^2.0.1",
    "ionic-angular": "3.9.5",
    "ionicons": "3.0.0",
    "jquery": "^3.4.1",
    "jspdf": "^1.5.3",
    "moment": "^2.26.0",
    "ngx-bootstrap": "^4.2.0",
    "ngx-pagination": "^3.2.1",
    "ngx-pinch-zoom": "^1.2.3",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "ts-md5": "^1.2.4",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^3.2.3",
    "@types/bootstrap": "^4.3.1",
    "@types/jquery": "^3.3.31",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "com.telerik.plugins.nativepagetransitions": {},
      "cordova-plugin-photo-library": {
        "PHOTO_LIBRARY_USAGE_DESCRIPTION": "To choose photos"
      },
      "cordova-sqlite-storage": {},
      "com-badrit-base64": {},
      "cordova-plugin-file": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-x-socialsharing": {
        "ANDROID_SUPPORT_V4_VERSION": "24.1.1+"
      },
      "cordova-plugin-crop": {},
      "cordova-plugin-filepath": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-camera": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-add-swift-support": {},
      "com-sarriaroman-photoviewer": {},
      "cordova-plugin-lottie-splashscreen": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-android-permissions": {},
      "cordova-base64-to-gallery": {},
      "cordova-plugin-streaming-media": {},
      "com.paypal.cordova.mobilesdk": {},
      "cordova-plugin-google-analytics": {
        "GMS_VERSION": "11.0.1"
      },
      "cordova-plugin-inapppurchase": {},
      "cordova-plugin-app-update": {}
    },
    "platforms": [
      "ios",
      "android"
    ]
  }
}

**Comment by timbru31** [comment]
>  "cordova-ios": "^4.5.5",

Only cordova >= 9.0.0 and cordova-ios >= 5.0.0 are supported.
