### ISSUE TITLE
iOS crashes on Startup. Nullpointer exception

### ISSUE THREAD

**Issue by tottt** [timbru31/cordova-plugin-lottie-splashscreen#224]
# Bug report

## What steps will reproduce the problem?

Create ionic react app
Follow https://ionicframework.com/docs/native/lottie-splash-screen
In App.tsx:
`import { LottieSplashScreen } from '@ionic-native/lottie-splash-screen'; `
Build and simulate in Xcode using capacitor
`ionic capacitor build ios`

## Expected output

App starts in simulator

## What do you see instead?

App crashes.

## Log file of the issue/error

```
2020-06-17 21:22:02.440536+0200 ***[4419:42165] WF: === Starting WebFilter logging for process XXX
2020-06-17 21:22:02.440784+0200 ***[4419:42165] WF: _WebFilterIsActive returning: NO
Loading network plugin
2020-06-17 21:22:02.618852+0200 ***[4419:42165] CAPKeyboard: resize mode - native
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file ***ios/capacitor-cordova-ios-plugins/sourcesstatic/CordovaPluginLottieSplashscreen/LottieSplashScreen.swift, line 223
2020-06-17 21:22:02.648838+0200 ***[4419:42165] Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file ***ios/capacitor-cordova-ios-plugins/sourcesstatic/CordovaPluginLottieSplashscreen/LottieSplashScreen.swift, line 223
(lldb) 
```

## Version information

cordova-lib@9.0.1 with:
  cordova-common@3.2.1
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment: 
  OS: darwin
  Node: v10.16.3
  npm: 6.14.5

## Checklist

-   [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
-   [x] I have added a valid version output
-   [ ] I have attached necessary information like a screenshot, example project or videos

**Comment by timbru31** [comment]
Can you please share your config.xml file and the version of this plugin you are using?

**Comment by tottt** [comment]
I'm using version **0.8.1** of cordova-plugin-lottie-splashscreen.
Sorry, no config.xml since I'm using  capacitor. Here's  the  capacitor.config.json
```
{
  "appId": "***",
  "appName": "***",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "build",
  "plugins": {
    "SplashScreen": {
      "launchShowDuration": 0
    }
  },
  "cordova": {}
}
```

**Comment by timbru31** [comment]
Weird, because line 123 uses (AFAIK) no things that could be `nil`. Please note that Capacitor is currently not supported and might not work: https://github.com/timbru31/cordova-plugin-lottie-splashscreen/issues/188#issuecomment-607204526

**Comment by tottt** [comment]
Please note that the Fatal Error happens on line 223 in LottieSplashScreen.swift

`self.webViewEngine.evaluateJavaScript("document.dispatchEvent(new Event('lottieAnimationStart'))", completionHandler: nil)`

Also note that I haven't called any method of LottieSplashScreen yet. Just importing the plugin.

**Comment by timbru31** [comment]
Oh, I see 🙈 - that the call to `animationEnded` - this might be `nil`. Could you share an example project or provide the steps to reproduce? This would speed up my investigation.

**Comment by tottt** [comment]
Thank's for your swift replies.
Will  provide more info tomorrow since it's getting rather late here in my timezone.

**Comment by timbru31** [comment]
I've reproduced the issue and this is sadly a bug in Capacitor that you need to report there. They emulate the `CDVPlugin` class, but do not provide a working `webViewEngine.evaluateJavaScript`, that's why a NPE is thrown.

**Comment by timbru31** [comment]
Good news, I've found the issue why the NPE is thrown and submitted a PR for capacitor.

**Comment by timbru31** [comment]
Capacitor v3.0.0-alpha.13 and v2.4.6 contain my fix.
