### ISSUE TITLE
java.lang.ClassNotFoundException: de.dustplanet.cordova.lottie.LottieSplashScreen in Angular 10 & ionic 5

### ISSUE THREAD

**Issue by cslegany** [timbru31/cordova-plugin-lottie-splashscreen#244]
# Bug report

## What steps will reproduce the problem?
Crashes on emulator just after fresh install

## Version information

    "@ionic-native/core": "^5.0.0",
    "@ionic-native/lottie-splash-screen": "^5.28.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "cordova-android": "^8.1.0",
    "cordova-plugin-androidx-adapter": "^1.1.1",
    "cordova-plugin-lottie-splashscreen": "^0.9.0",

## Checklist

-   [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
-   [ ] I have added a valid version output
-   [ ] I have attached necessary information like a screenshot, example project or videos

**Comment by timbru31** [comment]
Please refer to the README: https://github.com/timbru31/cordova-plugin-lottie-splashscreen#supported-platforms
