### ISSUE TITLE
Android Background Color without Alphabet

### ISSUE THREAD

**Issue by abomadi** [timbru31/cordova-plugin-lottie-splashscreen#255]
# Bug report
I was trying to assign #000000 as LottieBackgroundColor but it always return a white background instead.
## What steps will reproduce the problem?
Android build with `<preference name="LottieBackgroundColor" value="#000000" />`
Tested Emulator Pixel 2 28 API

Hoever if you put a color with alphabet it return it correctly !

## Expected output
Dark Black color
## What do you see instead?
White color

## Version information
cordova-plugin-lottie-splashscreen 0.9.0

## Please provide any additional information below.
Ionic 3 Environment, Cordova 9

I have changed the ColorHelper.kt to
```
fun ColorHelper.Companion.parseColor(@Size(min = 1) colorString: String): Int {
        return Color.parseColor(colorString)
}
```
This returned the expected result, any idea why this library is not used ?

**Comment by timbru31** [comment]
Can you please update your Android Studio installation? It seems you are hitting this bug from Android Studio: https://github.com/timbru31/cordova-plugin-lottie-splashscreen/issues/67#issuecomment-481021787

**Comment by timbru31** [comment]
To answer your second question:
I'm not using the `Color.parseColor` method, because Android uses the format `#AARRGGBB` (alpha are the first two letters), but web developers are more familiar with the CSS Color syntax which puts alpha at the end of the notation (see https://drafts.csswg.org/css-color/#hex-notation).

Upon a closer look I could use the method after the alpha value reversal though.

**Comment by timbru31** [comment]
> @timbru31 i have seen #67 before i believe it's different case, however i am using AS 4.1 as below
> 
> ```
> Android Studio 4.1
> Build #AI-201.8743.12.41.6858069, built on September 23, 2020
> Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> macOS 10.15.7
> ```

Thanks, I'll make myself a fresh debug app to test this.

**Comment by timbru31** [comment]
Small update, there seems to be an underlying parsing issue. The color from the preference string is parsed as #ff000000 (transparent), I'll investigate further!

**Comment by timbru31** [comment]
It's still (or again?) the AAPT parsing bug. The solution of #67 still works:

You can add the following to your build-extras.gradle file:
```
android {
    aaptOptions {
        additionalParameters "--keep-raw-values"
    }
}
```

I'll add this to the FAQ.md document.
