### ISSUE TITLE
Android spalsh screen not loading no errors

### ISSUE THREAD

**Issue by mrbdrm** [timbru31/cordova-plugin-lottie-splashscreen#272]
thank you for this plugin! 
i added the plugin and added the config same as in the example project 
```
         <!-- Lottie specific config -->
    <preference name="LottieRemoteEnabled" value="true" />
    <preference name="LottieLoopAnimation" value="true" />
```
```
            <!-- Lottie specific config -->
        <preference name="LottieAnimationLocation" value="https://assets.lottiefiles.com/datafiles/PEt3QhOjDXHDIGH/data.json" />
        <preference name="LottieBackgroundColor" value="#fff000a3" />
        <preference name="LottieEnableHardwareAcceleration" value="true" />
        <preference name="LottieWidth" value="350" />
        <preference name="LottieHeight" value="350" />
        <preference name="LottieCacheDisabled" value="true" />
```
my app launches but to a white screen then the index is loaded. 
do i need to do anything else in js? or is there something missing in my config?

**Comment by timbru31** [comment]
Please share your log from Android Studio/logcat. Native errors are not logged to the browser console. Besides that, please follow the issue template next time, it's there for a reason.

**Comment by mrbdrm** [comment]
sorry about that. 
these are the errors from android studio 
```
2021-01-24 20:04:38.363 2965-2965/net.mhale E/MyPluginLayout: --> zoomScale = 2.625
2021-01-24 20:04:38.450 2965-2965/net.mhale E/LottieSplashScreen: LottieAnimationLocation has to be configured!
2021-01-24 20:04:38.450 2965-2965/net.mhale E/LottieSplashScreen: The provided animation is invalid

**Comment by timbru31** [comment]
Which version of the plugin are you using?

**Comment by timbru31** [comment]
I've indeed noticed a small mistake from 6cd7b623404f8c0427f08bbd4dfdb5528bd0f6fb - I'll release v0.9.5

**Comment by mrbdrm** [comment]
Working! 
Thanks a lot 
i will be sure to donate for this project
