### ISSUE TITLE
splashscreen is undefined on android

### ISSUE THREAD

**Issue by mrbdrm** [timbru31/cordova-plugin-lottie-splashscreen#273]
# Bug report

## What steps will reproduce the problem?
run the code to hide the spashscreen 
`lottie.splashscreen.hide();`

## Expected output
the splash screen hide

## What do you see instead?
error on the console 
`VM195:1 Uncaught TypeError: Cannot read property 'hide' of undefined`

## Please provide any additional information below.
the animation works and i can hide it using the config. but i want to keep it a bit longer until some js function is over 

## Checklist

-   [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
-   [ ] I have added a valid version output
-   [ ] I have attached necessary information like a screenshot, example project or videos

**Comment by timbru31** [comment]
Are you calling this method after the `deviceready` event?

**Comment by mrbdrm** [comment]
Yes 
i tried on emulator and a real device.
from the console when i type lottie.splashscreen i see the undefined

**Comment by timbru31** [comment]
Could you share an example project that showcases the issue?
Some guidance how to Crete one: ttps://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by timbru31** [comment]
I've just re-checked the example project - the JS works as intended. This pretty much sounds like a bug in your application.

**Comment by mrbdrm** [comment]
im making an example project to test. i will update you.

**Comment by mrbdrm** [comment]
Found the issue 
changing corodva.js location to the last script to load on the page made it work.
if there is something you could do it will be good. since im using an editor that keep changing the location of cordova.js to the top of the page

**Comment by timbru31** [comment]
Can you share your `index.html`? What editor do you use so it's changed back?

**Comment by mrbdrm** [comment]
This is strange.
there is a script in my project that is loaded remotely. when made it local the issue is resolved. the position of cordova.js doesn't make a difference now. 
its working great now!

thank you for keeping up with my issue. 
cheers!

**Comment by timbru31** [comment]
Glad you’ve solved it!
