### ISSUE TITLE
lottie.splashscreen.once promise don't work

### ISSUE THREAD

**Issue by jaimeurzua** [timbru31/cordova-plugin-lottie-splashscreen#286]
# Bug report

With new update, lottie.splashscreen.once promise don't work

Launch app with Lottie splash.

try in console

lottie.splashscreen.once('lottieAnimationEnd').then(_ => { console.log("end"); });

promise remain pending so then code can not execute, app code with previous version work fine.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by timbru31** [comment]
Besides that, I've just retest the feature and it works as intended. Make sure to put run the coder **after** the deviceready event.
