### ISSUE TITLE
App Crashes On Launch

### ISSUE THREAD

**Issue by salemdomain** [timbru31/cordova-plugin-lottie-splashscreen#368]
# Bug report - I/System.out: Error adding plugin de.dustplanet.cordova.lottie.LottieSplashScreen.

## Expected output -
11/09 00:22:08: Launching 'app' on HUAWEI VOG-L29.
App restart successful without requiring a re-install.
$ adb shell am start -n "com.samsungAfrica.app/com.samsungAfrica.app.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: com.samsungAfrica.app | com.samsungAfrica.app.test
Waiting for application to come online: com.samsungAfrica.app | com.samsungAfrica.app.test
Connected to process 28222 on device 'huawei-vog_l29-DUM0219308015864'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/ActivityThread: Attach thread to application
I/ActivityThread: Init compatible state: true
D/HwFrameworkSecurityPartsFactory: HwFrameworkSecurityPartsFactory in.
I/HwFrameworkSecurityPartsFactory: add HwFrameworkSecurityPartsFactory to memory.
E/BehaviorCollectManager: Fail to acquire dataAnalyzerService...
W/ActivityThread: Application com.samsungAfrica.app is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
Connecting to com.samsungAfrica.app
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/.samsungAfrica.ap: Late-enabling -Xcheck:jni
E/.samsungAfrica.ap: Unknown bits set in runtime_flags: 0x8000
I/.samsungAfrica.ap: Reinit property: dalvik.vm.checkjni= false
    ReInitProperties: persist.vm.debug.dumpapi= false
D/ActivityThread: Attach thread to application
I/ActivityThread: Init compatible state: true
D/HwFrameworkSecurityPartsFactory: HwFrameworkSecurityPartsFactory in.
I/HwFrameworkSecurityPartsFactory: add HwFrameworkSecurityPartsFactory to memory.
E/BehaviorCollectManager: Fail to acquire dataAnalyzerService...
W/ActivityThread: Application com.samsungAfrica.app is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/System.out: Debugger has connected
    waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
Connected to the target VM, address: 'localhost:8311', transport: 'socket'
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/chatty: uid=10205(com.samsungAfrica.app) identical 1 line
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1410)
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.samsungAfrica.app#10205#256
    need clear apicache,because volumes changed,oldCnt=0 newCnt=1
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.samsungAfrica.app#10205#0
I/HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=1 newCnt=1
E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@c57ea96
I/HwPartIawareFactory: add android.common.HwPartIawareFactoryImpl to memory.
I/AwareBitmapCacher: init processName:com.samsungAfrica.app pid=28222 uid=10205
W/ComponentDiscovery: Class com.google.firebase.dynamicloading.DynamicLoadingRegistrar is not an found.
I/FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
I/FirebaseInitProvider: FirebaseApp initialization successful
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.samsungAfrica.app#10205#256
I/HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=1 newCnt=1
I/ActivityThread: finishPreloaded preloadStatus 0
V/ActivityThread: callActivityOnCreate
E/.samsungAfrica.ap: Invalid ID 0x00000000.
I/DecorView[]:  old windowMode:0 new windoMode:1
W/.samsungAfrica.ap: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
    Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/WebViewFactory: Loading com.google.android.webview version 95.0.4638.74 (code 463807434)
W/.samsungAfrica.ap: Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
    Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
    Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
    Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
    Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
I/cr_WVCFactoryProvider: Loaded version=95.0.4638.74 minSdkVersion=29 isBundle=true multiprocess=true packageId=3
E/.samsungAfrica.ap: Invalid ID 0x00000000.
    Invalid ID 0x00000000.
I/cr_LibraryLoader: Successfully loaded native library
I/cr_CachingUmaRecorder: Flushed 8 samples from 8 histograms.
E/chromium: [ERROR:network_service_instance_impl.cc(179)] Failed to grant sandbox access to network context data for /data/user/0/com.samsungAfrica.app/app_webview/Default with result 7: No such file or directory (2)
D/HwCustConnectivityManagerImpl: isBlockNetworkRequestByNonAis, INVALID_SUBSCRIPTION_ID
I/ConnectivityManager: requestNetwork and the calling app is: com.samsungAfrica.app
D/HwCustConnectivityManagerImpl: isBlockNetworkRequestByNonAis, INVALID_SUBSCRIPTION_ID
D/ActivityThread: add activity client record, r= ActivityRecord{b013b68 token=android.os.BinderProxy@8e6edea {com.samsungAfrica.app/com.samsungAfrica.app.MainActivity}} token= android.os.BinderProxy@8e6edea
D/Capacitor: Starting BridgeActivity
W/System.err: java.lang.ClassNotFoundException: de.dustplanet.cordova.lottie.LottieSplashScreen
W/System.err:     at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
        at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
        at org.apache.cordova.PluginManager.init(PluginManager.java:86)
        at com.getcapacitor.cordova.MockCordovaWebViewImpl.init(MockCordovaWebViewImpl.java:58)
W/System.err:     at com.getcapacitor.Bridge$Builder.create(Bridge.java:1276)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:72)
        at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:110)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1447)
        at android.app.Activity.performStart(Activity.java:8144)
W/System.err:     at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3922)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
W/System.err:     at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "de.dustplanet.cordova.lottie.LottieSplashScreen" on path: DexPathList[[zip file "/data/app/com.samsungAfrica.app-DnIEK5ZVRfN4kYt9xssvYg==/base.apk"],nativeLibraryDirectories=[/data/app/com.samsungAfrica.app-DnIEK5ZVRfN4kYt9xssvYg==/lib/arm64, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	... 25 more
I/System.out: Error adding plugin de.dustplanet.cordova.lottie.LottieSplashScreen.
I/BlockMonitor: dispatchingThrewException In MainThread
D/AndroidRuntime: Shutting down VM
I/QarthLog: [PatchStore] createDisableExceptionQarthFile
    [PatchStore] create disable file for com.samsungAfrica.app uid is 10205
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.samsungAfrica.app, PID: 28222
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
        at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
        at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
        at org.apache.cordova.PluginManager.init(PluginManager.java:86)
        at com.getcapacitor.cordova.MockCordovaWebViewImpl.init(MockCordovaWebViewImpl.java:58)
        at com.getcapacitor.Bridge$Builder.create(Bridge.java:1276)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:72)
        at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:110)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1447)
        at android.app.Activity.performStart(Activity.java:8144)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3922)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
I/Process: Sending signal. PID: 28222 SIG: 9
Disconnected from the target VM, address: 'localhost:8311', transport: 'socket'

## Checklist

-   [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
-   [ ] I have added a valid version output
-   [ ] I have attached necessary information like a screenshot, example project or videos

**Comment by timbru31** [comment]
Probably the same as https://github.com/timbru31/cordova-plugin-lottie-splashscreen/issues/188, Capacitor is not yet tested nor fully supported.

**Comment by YanDevDe** [comment]
I'm also having this issue on cordova as well. I'm using cordova android 10. iOS works fine! Using 0.9.6.

```
12-27 02:05:26.544 W/System.err(13920): java.lang.ClassNotFoundException: de.dustplanet.cordova.lottie.LottieSplashScreen
12-27 02:05:26.544 W/System.err(13920):         at java.lang.Class.classForName(Native Method)
12-27 02:05:26.544 W/System.err(13920):         at java.lang.Class.forName(Class.java:454)
12-27 02:05:26.544 W/System.err(13920):         at java.lang.Class.forName(Class.java:379)
12-27 02:05:26.544 W/System.err(13920):         at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:564)
12-27 02:05:26.544 W/System.err(13920):         at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:183)
12-27 02:05:26.544 W/System.err(13920):         at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:108)
12-27 02:05:26.544 W/System.err(13920):         at org.apache.cordova.PluginManager.init(PluginManager.java:96)
12-27 02:05:26.544 W/System.err(13920):         at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:119)
12-27 02:05:26.544 W/System.err(13920):         at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:152)
12-27 02:05:26.544 W/System.err(13920):         at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:227)
12-27 02:05:26.544 W/System.err(13920):         at io.pacglobal.pacapp.MainActivity.onCreate(MainActivity.java:39)
12-27 02:05:26.544 W/System.err(13920):         at android.app.Activity.performCreate(Activity.java:7994)
12-27 02:05:26.544 W/System.err(13920):         at android.app.Activity.performCreate(Activity.java:7978)
12-27 02:05:26.544 W/System.err(13920):         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
12-27 02:05:26.544 W/System.err(13920):         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
12-27 02:05:26.544 W/System.err(13920):         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
12-27 02:05:26.544 W/System.err(13920):         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
12-27 02:05:26.544 W/System.err(13920):         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-27 02:05:26.544 W/System.err(13920):         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-27 02:05:26.544 W/System.err(13920):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
12-27 02:05:26.544 W/System.err(13920):         at android.os.Handler.dispatchMessage(Handler.java:106)
12-27 02:05:26.544 W/System.err(13920):         at android.os.Looper.loop(Looper.java:223)
12-27 02:05:26.544 W/System.err(13920):         at android.app.ActivityThread.main(ActivityThread.java:7656)
12-27 02:05:26.544 W/System.err(13920):         at java.lang.reflect.Method.invoke(Native Method)
12-27 02:05:26.544 W/System.err(13920):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-27 02:05:26.544 W/System.err(13920):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
12-27 02:05:26.544 W/System.err(13920): Caused by: java.lang.ClassNotFoundException: Didn't find class "de.dustplanet.cordova.lottie.LottieSplashScreen" on path: DexPathList[[zip file "/data/app/~~3WopG4ubmjAfAT_H9AZRKQ==/io.pacglobal.pacapp-4KUA3QwqIYKbsnjkYwOrag==/base.apk"],nativeLibraryDirectories=[/data/app/~~3WopG4ubmjAfAT_H9AZRKQ==/io.pacglobal.pacapp-4KUA3QwqIYKbsnjkYwOrag==/lib/arm64, /system/lib64, /system_ext/lib64]]
12-27 02:05:26.544 W/System.err(13920):         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
12-27 02:05:26.544 W/System.err(13920):         at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
12-27 02:05:26.544 W/System.err(13920):         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
12-27 02:05:26.544 W/System.err(13920):         ... 26 more
12-27 02:05:26.544 I/System.out(13920): Error adding plugin de.dustplanet.cordova.lottie.LottieSplashScreen.
```

**Comment by YanDevDe** [comment]
v0.8.1 (which I used before) seems to be working well.

**Comment by timbru31** [comment]
A couple of helpful things for me to debug:
- Can you post a full build log?
- Did you try to remove and re-add the plugin?
- Can you provide an example project/repository?

**Comment by vovka-s** [comment]
Guys, I have found a solution to launch this plugin on Android on ionic6 + capacitor3
1. First of all your need to replace `jcenter` repo with `mavenCentral` in `android/build.gradle` due to jcenter is deprecated now
2. Then update `cordovaAndroidVersion` to  `10.1.1` in `android/variables.gradle`
3. The next problem is that capacitor does not support cordova plugins written on kotlin (discussed [here](https://github.com/ionic-team/capacitor/issues/4426)).

To fix it you need to
- Open **Android Studio --> Tools --> Kotlin --> Configure Kotlin in Project**. Then select the "capacitor-cordova-android-plugins" Module and configure.
- add `capacitor:sync:after` script to package.json like described [here](https://github.com/EinfachHans/cordova-plugin-advanced-imagepicker/issues/20#issuecomment-885523051) 

Script was modified by me to fix the version of androidx.core:core-ktx, so I paste it below
In package.json:
```
{
  "scripts": {
    ...
    "capacitor:sync:after": "node scripts/fix-capacitor-android-plugins-kotlin-version.js"
    ...
  }
}
```
The script file:
```
const fs = require("fs");

if (process.env.CAPACITOR_PLATFORM_NAME === 'android') {
  let file = fs.readFileSync('./android/capacitor-cordova-android-plugins/build.gradle', 'utf8');

  file = file.replace(/apply plugin: 'com.android.library'\n\s*\n/, `apply plugin: 'com.android.library'\r\nif(project.hasProperty('kotlin_version')) {\r\n    apply plugin: 'kotlin-android'\r\n}\r\n\r\n`);
  file = file.replace(/implementation "org.apache.cordova:framework:\$cordovaAndroidVersion"\n[ ]{4}\/\/ SUB-PROJECT DEPENDENCIES START/,
    `implementation "org.apache.cordova:framework:$cordovaAndroidVersion"\r\n    if(project.hasProperty('kotlin_version')) {\r\n        implementation "androidx.core:core-ktx:$androidxCoreVersion"\r\n        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"\r\n    }\r\n    // SUB-PROJECT DEPENDENCIES START`);

  fs.writeFileSync('./android/capacitor-cordova-android-plugins/build.gradle', file);
}
```
4. After that I got an error like "Can't call a method on null object reference" in **LottieSplashScreen.kt:284**:
`webView.engine.evaluateJavascript("document.dispatchEvent(new Event('lottieAnimationStart'))") { }`
`webView.engine` is null. I dont know why. I dont use this event in js, so I just comment that row and 3 others and made a patch:
```
diff --git a/node_modules/cordova-plugin-lottie-splashscreen/src/android/LottieSplashScreen.kt b/node_modules/cordova-plugin-lottie-splashscreen/src/android/LottieSplashScreen.kt
index 7edb94d..42e614b 100644
--- a/node_modules/cordova-plugin-lottie-splashscreen/src/android/LottieSplashScreen.kt
+++ b/node_modules/cordova-plugin-lottie-splashscreen/src/android/LottieSplashScreen.kt
@@ -281,11 +281,12 @@ class LottieSplashScreen : CordovaPlugin() {
         animationView.addAnimatorListener(
             object : Animator.AnimatorListener {
                 override fun onAnimationStart(animation: Animator) {
-                    webView.engine.evaluateJavascript("document.dispatchEvent(new Event('lottieAnimationStart'))") { }
+                    // webView.engine.evaluateJavascript("document.dispatchEvent(new Event('lottieAnimationStart'))") { }
                 }
 
                 override fun onAnimationEnd(animation: Animator) {
-                    webView.engine.evaluateJavascript("document.dispatchEvent(new Event('lottieAnimationEnd'))") { }
+                    // webView.engine.evaluateJavascript("document.dispatchEvent(new Event('lottieAnimationEnd'))") { }
                     val hideAfterAnimationDone = preferences.getBoolean(
                         "LottieHideAfterAnimationEnd",
                         false
@@ -297,11 +298,11 @@ class LottieSplashScreen : CordovaPlugin() {
                 }
 
                 override fun onAnimationCancel(animation: Animator) {
-                    webView.engine.evaluateJavascript("document.dispatchEvent(new Event('lottieAnimationCancel'))") { }
+                    // webView.engine.evaluateJavascript("document.dispatchEvent(new Event('lottieAnimationCancel'))") { }
                 }
 
                 override fun onAnimationRepeat(animation: Animator) {
-                    webView.engine.evaluateJavascript("document.dispatchEvent(new Event('lottieAnimationRepeat'))") { }
+                    // webView.engine.evaluateJavascript("document.dispatchEvent(new Event('lottieAnimationRepeat'))") { }
                 }
             }
         )

```
**After that manipulations lottie became work!** :clap: :clap: :clap: :clap: :clap: :clap::face_with_head_bandage: 

My `android/build.gradle`:
```
buildscript {
    ext.kotlin_version = '1.6.10'

    repositories {
        google()
        mavenCentral()
        maven { url 'https://developer.huawei.com/repo/' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.huawei.agconnect:agcp:1.6.3.300'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://developer.huawei.com/repo/' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

My `android/variables.gradle`:
```
ext {
    minSdkVersion = 22
    compileSdkVersion = 30
    targetSdkVersion = 30
    androidxActivityVersion = '1.3.1'
    androidxAppCompatVersion = '1.3.1'
    androidxCoordinatorLayoutVersion = '1.1.0'
    androidxCoreVersion = '1.6.0'
    androidxFragmentVersion = '1.3.0'
    junitVersion = '4.13.1'
    androidxJunitVersion = '1.1.2'
    androidxEspressoCoreVersion = '3.3.0'
    cordovaAndroidVersion = '10.1.1'
}

```

**Comment by timbru31** [comment]
Appreciated your debugging and the workaround 👏 

About the webViewEngine being undefined.... this sounds similar to the iOS fix I've submitted: https://github.com/ionic-team/capacitor/pull/4039 - sadly this need to be fixed by the Capacitor team.
Can you report that the webView.engine.evaluateJavascript is undefined for Android?

**Comment by vovka-s** [comment]
> Appreciated your debugging and the workaround :clap:

Thanks)
Created an issue in capacitor's repo: https://github.com/ionic-team/capacitor/issues/5390
Please leave additional comments if a made any mistake

**Comment by dtarnawsky** [comment]
Should be resolved by this [PR](https://github.com/timbru31/cordova-plugin-lottie-splashscreen/pull/438)
