### ISSUE TITLE
iOS - Build fails

### ISSUE THREAD

**Issue by niconaso** [timbru31/cordova-plugin-lottie-splashscreen#37]
When I try to build for iOS it throws this message:

/Users/niconaso/development/workspace/cabal-mobile/platforms/ios/Cabal Móvil/Plugins/cordova-plugin-lottie-splashscreen/LottieSplashScreen.swift:1:8: error: no such module 'Lottie'
import Lottie
       ^

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/niconaso/development/workspace/cabal-mobile/platforms/ios/Cabal Móvil/Plugins/cordova-plugin-fingerprint-aio/Fingerprint.swift
	CompileSwift normal x86_64 /Users/niconaso/development/workspace/cabal-mobile/platforms/ios/Cabal Móvil/Plugins/cordova-plugin-lottie-splashscreen/LottieSplashScreen.swift
	CompileSwift normal x86_64 /Users/niconaso/development/workspace/cabal-mobile/platforms/ios/Cabal Móvil/Plugins/cordova-plugin-lottie-splashscreen/UIColorHelper.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(4 failures)
CordovaError: Promise rejected with non-error: 'Error code 65 for command: xcodebuild with args: -xcconfig,/Users/niconaso/development/workspace/cabal-mobile/platforms/ios/cordova/build-debug.xcconfig,-workspace,Cabal Móvil.xcworkspace,-scheme,Cabal Móvil,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/Users/niconaso/development/workspace/cabal-mobile/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/niconaso/development/workspace/cabal-mobile/platforms/ios/build/sharedpch,EMBEDDED_CONTENT_CONTAINS_SWIFT = YES,ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO,LD_RUNPATH_SEARCH_PATHS = "@executable_path/Frameworks",-UseModernBuildSystem=0'
    at cli.catch.err (/Users/niconaso/.nvm/versions/node/v8.11.1/lib/node_modules/cordova/bin/cordova:30:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.

Can you help me?
Thanks!!

**Comment by niconaso** [comment]
Hi @timbru31 , first of all nice I want to thank you for the job you've done with this plugin 😄. 
I installed the version published on NPM, I think is the stable one.

**Comment by timbru31** [comment]
Please try cordova-plugin-lottie-splashscreen@0.2.21 - this one worked for me in the following cases:
- installation when no platform was present (i.e. in config.xml and then cordova platform add ios
- installation when platform was present (i.e. cordova plugin add cordova-plugin-lottie-splashscreen@0.2.21
- installation/packaging in Ionic Appflow

**Comment by timbru31** [comment]
v0.3.0 has been published to npm. Please let me know if this issue still persists. If yes I'm happy to re-open this issue.
