### ISSUE TITLE
Build Error with XCode Legacy Build System

### ISSUE THREAD

**Issue by hoi4** [timbru31/cordova-plugin-lottie-splashscreen#41]
Hi,

first of all, thank you for your work!

I would like to use your plugin with Ionic in a project where I need to use **XCode's Legacy Build System** for building the app. 

For testing I created an empty IonicV3 project with the following command:
`ionic start myApp tabs --type=ionic-angular` and installed your plugin together with the Ionic-Native wrapper (see https://ionicframework.com/docs/v3/native/lottie-splash-screen/)

Note: The Cordova build will only use the Legacy Build System when doing the following steps:

- use `ionic cordova build ios` (will use new build system)
- open the generated XCode project and set the Build System to Legacy in File -> Workspace Settings
- run the XCode build
- repeat `ionic cordova build ios`: This time it will use the legacy build system

Unfortunately the cordova build using the legacy build system fails with the following error:

```
The following build commands failed:
        Ld .../TestProject/myApp/platforms/ios/build/emulator/Lottie.framework/Lottie normal x86_64
(1 failure)
```

The specific error is the following:

```
**ld: framework not found Lottie
clang: error: linker command failed with exit code 1 (use -v to see invocation)**
```

FYI: During the installation of the plugin, I get the following **warnings**:
```
[!] The MyApp [Debug] target overrides the LD_RUNPATH_SEARCH_PATHS build setting defined in Pods/Target Support Files/Pods-MyApp/Pods-MyApp.debug.xcconfig. This can lead to problems with the CocoaPods installation
    - Use the $(inherited) flag, or
    - Remove the build settings from the target.

[!] The MyApp [Release] target overrides the LD_RUNPATH_SEARCH_PATHS build setting defined in Pods/Target Support Files/Pods-MyApp/Pods-MyApp.release.xcconfig. This can lead to problems with the CocoaPods installation
    - Use the $(inherited) flag, or
    - Remove the build settings from the target.
```

I hope you can help me with this!

Thanks in advance!

**Comment by timbru31** [comment]
Strange it worked for me with Xcode 10.1 and the legacy build settings. Have you made sure to open the `MyApp.xcworkspace` and not the `MyApp.xcodeproj` when switching to the legacy build system?

**Comment by hoi4** [comment]
- I have installed cocoapods and installed lottie-ios using `pod install`, even manually when getting the error
- Yes, I am opening the xcworkspace

It is not the XCode legacy build that fails, but the ionic **cordova build after setting the build system to legacy in XCode**

**Comment by timbru31** [comment]
Great, thanks for your feedback. Just to make sure: what version of Xcode are you using? Tomorrow I can debug the issue further on another machine.

**Comment by hoi4** [comment]
I am using `Version 10.1 (10B61)`

**Comment by hoi4** [comment]
I just made some more tests and found out, that the cordova build works when forcing it to use the new build system by using
`ionic cordova build ios -- --buildFlag="-UseModernBuildSystem=0"`

This way I can use the Legacy Build System in XCode (which is needed by some cordova plugins that I am using), but use the new build system for the cordova build.

**Comment by hoi4** [comment]
The XCode build fails when there is more than one plugin that uses cocoapods.

- I installed the lottie-splashscreen plugin -> Build worked fine
- When installing phonegap-plugin-push (uses the FirebaseMessaging pod) the XCode build fails.

I think this has to do with the warning that I wrote above: 
```
[!] The MyApp [Debug] target overrides the LD_RUNPATH_SEARCH_PATHS build setting defined in Pods/Target Support Files/Pods-MyApp/Pods-MyApp.debug.xcconfig. This can lead to problems with the CocoaPods installation
    - Use the $(inherited) flag, or
    - Remove the build settings from the target.

[!] The MyApp [Release] target overrides the LD_RUNPATH_SEARCH_PATHS build setting defined in Pods/Target Support Files/Pods-MyApp/Pods-MyApp.release.xcconfig. This can lead to problems with the CocoaPods installation
    - Use the $(inherited) flag, or
    - Remove the build settings from the target.
```

When there are multiple plugins that use pods, the search path is somehow messed up.

**Comment by timbru31** [comment]
Thanks, I'll debug this.

**Comment by timbru31** [comment]
Could you possibly post the output of your `Podfile`?

**Comment by hoi4** [comment]
This is my PodFile:
```
# DO NOT MODIFY -- auto-generated by Apache Cordova
platform :ios, '8.0'
target 'MyApp' do
	project 'MyApp.xcodeproj'
	pod 'lottie-ios', '2.5.2'
	pod 'FirebaseMessaging', '~> 2.0.0'
end

```

**Comment by hoi4** [comment]
Any news about the issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by timbru31** [comment]
I'm currently working on the 0.6.0 release which upgrades lottie-ios to the next major version (3.0.4).  
The update will require Cordova CLI v9 and cordova-ios v5 - are you able to upgrade (or already have)?
