### ISSUE TITLE
not found, app crash

### ISSUE THREAD

**Issue by isaiass18** [timbru31/cordova-plugin-lottie-splashscreen#44]
Could you please put an example working, I install the plugin and the application does not open.

**Comment by timbru31** [comment]
Sure, thanks for the suggestion :)  
In the meantime, to help your issue:
* What steps did you take to install the plugin?
* What versions of Cordova and the platforms are you using?
* What platform(s) are affected?
* Did you correctly configure the config.xml values? The animation location is a mandatory prop. :)

**Comment by timbru31** [comment]
A working example has been added (#48) in the example folder.

**Comment by isaiass18** [comment]
> Sure, thanks for the suggestion :)
> In the meantime, to help your issue:
> 
> * What steps did you take to install the plugin?
> * What versions of Cordova and the platforms are you using?
> * What platform(s) are affected?
> * Did you correctly configure the config.xml values? The animation location is a mandatory prop. :)


cordova plugin add cordova-plugin-lottie-splashscreen
8.1.2 (cordova-lib@8.1.1)
defaultBuildToolsVersion="27.0.1" //String
      defaultMinSdkVersion=19 //Integer - Minimum requirement is Android 4.4
      defaultTargetSdkVersion=27 //Integer - We ALWAYS target the latest by default
      defaultCompileSdkVersion=27 //Integer - We ALWAYS compile with the latest by default

**Comment by timbru31** [comment]
Thanks for your details, some questions are still missing though, could you possibly answer them? Also, did the example project help you`?

* What steps did you take to install the plugin?
* Did you correctly configure the config.xml values? The animation location is a mandatory prop. :)
