### ISSUE TITLE
android build error

### ISSUE THREAD

**Issue by Arun-S0** [timbru31/cordova-plugin-lottie-splashscreen#468]
> Task :app:compileDebugKotlin FAILED
e: platforms\android\app\src\main\kotlin\de\dustplanet\cordova\lottie\LottieSplashScreen.kt: (33, 28): Type mismatch: inferred type is String? but String was expected

FAILURE: Build failed with an exception.

![image](https://user-images.githubusercontent.com/111427281/185092163-3004aa83-3df8-4e7f-a5c8-5eebd25e4a73.png)

**Comment by timbru31** [comment]
Interesting. Can you open Android Studio and check the installed Gradle version by any chance?

**Comment by Arun-S0** [comment]
![image](https://user-images.githubusercontent.com/111427281/185345708-1eb4583d-3129-4fdc-8df6-e910502c327c.png)

**Comment by timbru31** [comment]
I've published a new release, please could you re-test if the issue still persists? Happy to re-open if so!
