### ISSUE TITLE
New npm release needed

### ISSUE THREAD

**Issue by martinglover** [timbru31/cordova-plugin-lottie-splashscreen#517]
# Bug 
The "recommended" npm install of `cordova-plugin-lottie-splashscreen` installs release 0.9.6 from March 2021, and is incompatible with the latest Capacitor/Ionic
These issues have been fixed in master but we just need a release so the default install contains these fixes, I'm sure many people would appreciate this.

## What steps will reproduce the problem?
`npm i cordova-plugin-lottie-splashscreen`

## Expected output
I like to be able to install an up to date release that contains the multitude of updates that have been implemented since 2021 including compatibility fixes for Capacitor 4

## What do you see instead?
Release 0.9.6 from March 2021

## Version information
Ionic 6
Capacitor 4
Node 18
Npm 9

**Comment by timbru31** [comment]
Yes indeed a release is overdue. Thanks for the reminder 👍

**Comment by timbru31** [comment]
v0.10.0 is now published.
