### ISSUE TITLE
Background splash screen disappear

### ISSUE THREAD

**Issue by richarZero22** [timbru31/cordova-plugin-lottie-splashscreen#65]
Hi, I have a question, when splash screen show It has a white background (no background in animation), if I disabled AutoHide it background hide but animation no. how can I show undefined time this background? Thanks you and sorry for my English

**Comment by timbru31** [comment]
If I understand you correctly you want a transparent background? Set the background color property to `ffffffff`

**Comment by richarZero22** [comment]
Sorry, I don't explained correctly, the splash screen has background and the animation the same, the background of splash screen disappear after some time and animation stay over application, this ocurrence if I disable the auto hide, next I leave a link with a example video 

https://drive.google.com/file/d/12Q8K889R026izggruigPMpwY8uW-wHrS/view

thanks!

**Comment by timbru31** [comment]
Could you share your animation and config.xml files with me? Speeds up debugging for me :)
