### ISSUE TITLE
Use Xcode 8.x to migrate the code to Swift 3.

### ISSUE THREAD

**Issue by ojulianos** [timbru31/cordova-plugin-lottie-splashscreen#77]
# Bug report

Showing All Messages
:-1: Value for SWIFT_VERSION cannot be empty. (in target 'MyApp')

## What steps will reproduce the problem?
Run iOS error

## Log file of the issue/error
error: Value for SWIFT_VERSION cannot be empty. (in target 'MyBelt Professor')

## Version information
cordova-lib@9.0.1 with:
  cordova-common@3.1.0
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment: 
  OS: darwin
  Node: v10.15.3
  npm: 6.4.1

Plugins:
  cordova-plugin-app-version
  cordova-plugin-device
  cordova-plugin-ionic-keyboard
  cordova-plugin-ionic-webview
  cordova-plugin-lottie-splashscreen
  cordova-plugin-network-information
  cordova-plugin-splashscreen
  cordova-plugin-statusbar
  cordova-plugin-whitelist
  cordova-sqlite-storage

iOS platform:
  Xcode 10.1
  Build version 10B61

config.xml <<EOF
<?xml version='1.0' encoding='utf-8'?>
<widget id="br.com.mybelt.professor" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>MyBelt Professor</name>
    <description>Aplicativo para professor MyBelt.</description>
    <author email="suporte@mybelt.com.br" href="https://mybelt.com.br/">Suporte MyBelt</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="19" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="LottieRemoteEnabled" value="true" />
    <preference name="LottieLoopAnimation" value="true" />
    <platform name="android">
        <preference name="LottieAnimationLocation" value="assets/faixa.json" />
        <preference name="LottieBackgroundColor" value="#fff000a3" />
        <preference name="LottieEnableHardwareAcceleration" value="true" />
        <preference name="LottieWidth" value="350" />
        <preference name="LottieHeight" value="350" />
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <preference name="LottieAnimationLocation" value="assets/faixa.json" />
        <preference name="LottieCancelOnTap" value="true" />
        <preference name="LottieFullScreen" value="true" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
    </platform>
    <plugin name="cordova-plugin-whitelist" spec="~1.3.3" />
    <plugin name="cordova-plugin-statusbar" spec="~2.4.2" />
    <plugin name="cordova-plugin-device" spec="~2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="~5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^3.0.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
    <plugin name="cordova-sqlite-storage" spec="3.1.0" />
    <allow-navigation href="http://192.168.1.10:8100" sessionid="09663f62" />
    <engine name="ios" spec="5.0.0" />
    <engine name="android" spec="7.1.4" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreenDelay" value="3000" />
</widget>

EOF

package.json <<EOF
{
  "name": "MyBeltProfessor",
  "version": "0.0.1",
  "author": "MyBelt Aplicativos para JiuJitsu",
  "homepage": "https://mybelt.com.br/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@ionic-native/app-version": "^5.7.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/lottie-splash-screen": "^5.7.0",
    "@ionic-native/network": "^5.7.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.0.0",
    "@ionic/storage": "^2.2.0",
    "ajv": "^6.9.1",
    "cordova-android": "7.1.4",
    "cordova-ios": "4.5.5",
    "cordova-plugin-app-version": "0.1.9",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^3.1.2",
    "cordova-plugin-lottie-splashscreen": "^0.6.0",
    "cordova-plugin-network-information": "2.0.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "3.1.0",
    "core-js": "^2.5.4",
    "rxjs": "^6.5.0",
    "zone.js": "~0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.12.3",
    "@angular-devkit/build-angular": "~0.12.3",
    "@angular-devkit/core": "~7.2.3",
    "@angular-devkit/schematics": "~7.2.3",
    "@angular/cli": "~7.2.3",
    "@angular/compiler": "~7.2.2",
    "@angular/compiler-cli": "~7.2.2",
    "@angular/language-service": "~7.2.2",
    "@ionic/angular-toolkit": "~1.3.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.12.0",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~8.0.0",
    "tslint": "~5.12.0",
    "typescript": "~3.1.6"
  },
  "description": "Aplicativo para professores utilizando o sistema MyBelt de Gerenciamento de Academias",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-sqlite-storage": {},
      "cordova-plugin-app-version": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-lottie-splashscreen": {}
    },
    "platforms": [
      "android",
      "ios"
    ]
  }
}
EOF

## Checklist

-   [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
-   [ ] I have added a valid version output
-   [ ] I have attached necessary information like a screenshot, example project or videos

**Comment by timbru31** [comment]
Please mind the README: https://github.com/timbru31/cordova-plugin-lottie-splashscreen#caveats - either upgrade cordova-ios (recommended) or downgrade this plugin to v0.5.0

**Comment by ojulianos** [comment]
I make the changes on README then 

** BUILD FAILED **

Command finished with error code 65: xcodebuild -workspace,MyBelt Professor.xcworkspace,-scheme,MyBelt Professor,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/Users/juliano/Sites/Apps/mybelt_professor2/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/juliano/Sites/Apps/mybelt_professor2/platforms/ios/build/sharedpch
xcodebuild: Command failed with exit code 65
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/juliano/Sites/Apps/mybelt_professor2/node_modules/cordova-common/src/superspawn.js:125:23)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios --verbose exited with exit code 65.

**Comment by timbru31** [comment]
That unfortunately does not help. Have you upgraded cordova-ios? Or downgraded the plugin?

**Comment by ojulianos** [comment]
I downgrade the plugin to 5.0.0 and the app run on android but don't on iOS

**Comment by ojulianos** [comment]
# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!
target 'MyBelt Professor' do
	project 'MyBelt Professor.xcodeproj'
	pod 'lottie-ios', '~> 3.0.4'
end

**Comment by ojulianos** [comment]
Now I compile the app but the splash animation don't work like I imagine, first shows a splash image, then shows the animation for 1 second and then shows the splash image again

**Comment by timbru31** [comment]
This plugin is meant as a replacement for the cordova-plugin-splashscreen, install one of them. If another plugin requires the stock one, disable the SplashScreen as described here: https://github.com/apache/cordova-plugin-splashscreen#configxml 

> splash animation don't work like I imagine
Make sure to configure your desired timings...

**Comment by dcherniy** [comment]
Also having the same exact issue despite using cordova 9.0.0 and cordova-ios 5.0.1. Downgrading to 5.x.x presents it's own problems on Cordova 9 since it uses `requireCordovaModule`, but that's an Ionic issue.

**Comment by timbru31** [comment]
Can you please elaborate? There are multiple „issues“ ranging from compilation errors to misconfigurations
