### ISSUE TITLE
LottieSplashScreen import doesn't work in React

### ISSUE THREAD

**Issue by idreamer** [timbru31/cordova-plugin-lottie-splashscreen#777]
# Bug report
I've tried to load the plugin after installing. But it returns an error below when I try to create Android app build. 
```
Module not found: Error: Can't resolve 'cordova-plugin-lottie-splashscreen'
```

## Checklist

-   [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
-   [ ] I have added a valid version output
-   [ ] I have attached necessary information like a screenshot, example project or videos

**Comment by timbru31** [comment]
Without any information I am sadly unable to help.
Please fill out the template and or provide a sample project for debugging.
