### ISSUE TITLE
local json not working 

### ISSUE THREAD

**Issue by ansarikhurshid786** [timbru31/cordova-plugin-lottie-splashscreen#82]
I am trying to load json from local as below: 
`this.lottieSplashScreen.show("assets/72.json", false);`

I have 72.json file in assets folder. 

I am getting promise response success with "OK" but not visible in view. 

Same thing working fine with remote url as below : 
`this.lottieSplashScreen.show("https://assets3.lottiefiles.com/datafiles/MUp3wlMDGtoK5FK/data.json", true);`

can anyone facing same issue?

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps me to debug the issue further and to provide a solution much faster. With important information missing, I unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

Besides that try to load the `72.json` from `www/assets/72.json` instead.

**Comment by ansarikhurshid786** [comment]
Thanks I will check as you suggested...
